In [ ]:
import torch

In [ ]:
data = [[1,2],[3,4]]

In [ ]:
x = torch.tensor(data)
print(x.is_cuda)

x=x.cuda()
print(x.is_cuda)
x=x.cpu()
print(x.is_cuda)

False
True
False


## 텐서 소개 및 생성 방법
* PyTorch에서의 텐서(tensor)는 기능적으로 넘파이(NumPy)와 매우 유사하다.
* 기본적으로 다차원 배열을 처리하기에 적합한 자료구조로 이해할 수 있다.
* PyTorch의 텐서는 "자동 미분"기능을 제공한다.

### 1) 텐서의 속성
* 텐서의 기본 속성으로는 다음과 같은 것들이 있다.

    * 모양(shape)
    * 자료형(data type)
    * 저장된 장치

In [ ]:
# 3행 4열짜리 텐서를 생성
tensor = torch.rand(3,4)

print(tensor)
# 텐서의 모양 (차원 구조) 확인
print(f"shape:{tensor.shape}")
# 텐서의 자료형
print(f"Data type {tensor.dtype}")
# 텐서가 CPU에 있는지, GPU에 있는지 확인
print(f"device {tensor.device}")

tensor([[0.8488, 0.1271, 0.4081, 0.8312],
        [0.6592, 0.8759, 0.8317, 0.4854],
        [0.1602, 0.7377, 0.3778, 0.5250]])
shape:torch.Size([3, 4])
Data type torch.float32
device cpu


### 2)텐서 초기화

* 리스트 데이터에서 직접 텐서를 초기화할 수 있다.

In [ ]:
data = [
    [1,2],
    [3,4]
]
x = torch.tensor(data)

print(x)

tensor([[1, 2],
        [3, 4]])


* NumPy 배열에서 텐서을 초기화할 수 있다.

In [ ]:
a = torch.tensor([5])
b = torch.tensor([7])


c=(a + b).numpy()
print(c)
print(type(c))

result = c + 10
tensor = torch.from_numpy(result)
print(tensor)
print(type(tensor))

[12]
<class 'numpy.ndarray'>
tensor([22])
<class 'torch.Tensor'>


### 3) 다른 텐서로부터 텐서 초기화하기

* 다른 텐서의 정보를 토대로 텐서를 초기화할 수 있다.
* 텐서의 속성: 모양(shape), 자료형(data type)

In [ ]:
x = torch.tensor([
    [5,7],
    [1,2]
])

# x와 같은 모양과 자료형을 가지지만, 값이 1인 텐서 생성
x_ones = torch.ones_like(x)
print(x_ones)

# x와 같은 모양을 가지되, 자료형은 float으로 덮어쓰고, 값은 랜덤으로 채우기
x_rand = torch.rand_like(x, dtype = torch.float32) #uniform distribution[0,1)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1052, 0.5718],
        [0.1941, 0.3126]])


## 텐서의 형변환 및 차원조작
* 텐서는 넘파이(NumPy) 배열처럼 조작할 수 있다.

### 1) 텐서의 특정 차원 접근하기
    
* 텐서의 원하는 차원에 접근할 수 있다.

In [ ]:
tensor = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(tensor[0]) #first row
print(tensor[:,0]) #first column
print(tensor[...,-1]) # last column

tensor([1, 2, 3, 4])
tensor([1, 5, 9])
tensor([ 4,  8, 12])


### 2) 텐서 이어붙이기 (concatenate)
*두 텐서를 이어 붙여 연결하여 새로운 텐서를 만들 수 있다.

In [ ]:
tensor = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

# dim: 텐서를 이어 붙이기 위한 축
# 0번 축(행)을 기준으로 이어 붙이기
result = torch.cat([tensor, tensor, tensor], dim=0)
print(result)

result = torch.cat([tensor, tensor, tensor],dim = 1)
print(result)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
        [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]])


###3) 텐서 형번환(type casting)

* 텐서의 자료형(정수, 실수 등)을 변환할 수 있다.

In [ ]:
a = torch.tensor([2],dtype=torch.int)
b = torch.tensor([5.0])

print(a.dtype)
print(b.dtype)

# 텐서 a는 자동으로 float32형으로 형변환 처리
print(a+b)

# 텐서 b를 int32형으로 형변환하여 덧셈 수행
print(a+b.type(torch.int32))

torch.int32
torch.float32
tensor([7.])
tensor([7], dtype=torch.int32)


### 4) 텐서의 모양 변경

* view()는 텐서의 모양을 변경할 때 사용한다.
* 이때, 텐서(tensor)의 순서는 변경되지 않는다.

In [ ]:
# view()는 텐서의 모양을 변경할 때 사용한다.
# 이때, 텐서(tensor)의 순서는 변경되지 않는다.
a = torch.tensor([1,2,3,4,5,6,7,8])
b = a.view(4,2)
print(b)

#a의 값을 변경하면 b도 변경(주소값을 변경하고 있음)
a[0] = 7
print(b)

#a의 값을 복사(copy)한 뒤에 변경
c = a.clone().view(4,2)
a[0] = 9
print(c)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


### 5) 텐서의 차원 교환

* 하나의 텐서에서 특정한 차원끼리 순서를 교체할 수 있다.

In [ ]:
a = torch.rand((64,32,3))
print(a.shape)

b = a.permute(2,1,0) #차원 자체를 교환
# (2번째 축, 1번째 축, 0번째 축)의 형태가 되도록 한다.
print(b.shape)

torch.Size([64, 32, 3])
torch.Size([3, 32, 64])


## 텐서의 연산과 함수

### 1) 텐서의 연산
* 텐서에 대하여 사칙연산 등 기본적인 연산을 수행할 수 있다.

In [ ]:
# 같은 크기를 가진 두 개의 텐서에 대하여 사칙연산 가능
# 기본적으로 요소별(element-wise) 연산

a = torch.tensor([
    [1,2],
    [3,4]
])

b = torch.tensor([
    [5,6],
    [7,8]
])

#같은 위치에 대하여 계산됨
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


* 행렬 곱을 수행할 수 있다.

In [ ]:
a = torch.tensor([
    [1,2],
    [3,4]
])

b = torch.tensor([
    [5,6],
    [7,8]
])

#행렬 곱(matrix multiplication) 수행
print(a.matmul(b))
print(torch.matmul(a,b))

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


### 2) 텐서의 평균 함수
* 텐서의 평균(mean)을 계산할 수 있다.

In [ ]:
a = torch.Tensor([
    [1,2,3,4],
    [5,6,7,8]
])

print(a)
print(a.mean()) #전체 원소에 대한 평균
print(a.mean(dim=1)) #각 열 방향에 대하여 평균
print(a.mean(dim=0)) #각 행 방향에 대하여 평균

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(4.5000)
tensor([2.5000, 6.5000])
tensor([3., 4., 5., 6.])


### 3) 텐서의 차원 줄이기 혹은 늘리기

* unsqueeze() 함수는 크기가 1인 차원을 추가한다.
    
    * 배치(batch)차원을 추가하기 위한 목적으로 흔히 사용된다.

* squeeze()함수는 크기가 1인 차원을 제거한다.

In [ ]:
a = torch.tensor([
    [1,2,3,4],
    [5,6,7,8]
])

print(a.shape)
#첫 번째 축에 자원 추가
a = a.unsqueeze(0)
print(a)
print(a.shape)

#네 번째 축에 자원 추가
a = a.unsqueeze(3)
print(a)
print(a.shape)


#첫 번째 축에 자원 제거
a = a.squeeze(0)
print(a)
print(a.shape)

torch.Size([2, 4])
tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])
torch.Size([1, 2, 4])
tensor([[[[1],
          [2],
          [3],
          [4]],

         [[5],
          [6],
          [7],
          [8]]]])
torch.Size([1, 2, 4, 1])
tensor([[[1],
         [2],
         [3],
         [4]],

        [[5],
         [6],
         [7],
         [8]]])
torch.Size([2, 4, 1])


## 자동 미분과 기울기 (Gradient)

* PyTorch에서는 연산에 대하여 자동 미분을 수행할 수 있다.

    * **z.grad_fn**: 이 연산이 어떻게 만들어졌는지를 알려주는 함수 (덧셈이면 <AddBackward0>)
    * **requires_grad=True** : 설정하면 PyTorch는 기울기를 추적
    * **backward**: 계산 그래프를 따라 자동으로 미분을 수행하고,
requires_grad=True인 텐서들의 .grad에 결과를 채워줌
    * **

In [4]:
import torch

# requires_grad를 설정할 때만 기울기 추적
x = torch.tensor([3.0, 4.0], requires_grad=True)
y = torch.tensor([1.0, 2.0], requires_grad=True)
z = x + y

print(z)
print(z.grad_fn)

out = z.mean()
print(out)
print(out.grad_fn)

out.backward()
print(x.grad)
print(y.grad)
print(z.grad)

tensor([4., 6.], grad_fn=<AddBackward0>)
tensor(5., grad_fn=<MeanBackward0>)
tensor([0.5000, 0.5000])
tensor([0.5000, 0.5000])
None


<ipython-input-4-e1305e6ebef4>:18: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print(z.grad)


* 일반적으로 모델을 학습할 때는 기울기(gradient)를 추적한다.

* 하지만, 학습된 모델을 사용할 때는 파라미터를 업데이트하지 않으므로, 기울기를 추적하지 않는 것이 일반적이다.

    * **no_grad()** 블록 내에서는 requires_grad=True가 강제로 꺼짐

In [7]:
temp = torch.tensor([3.0, 4.0], requires_grad=True)
print(temp.requires_grad)
print((temp ** 2).requires_grad)

# 기울기 추적을 하지 않기 때문에 계산 속도가 더 빠르다
with torch.no_grad():
    temp = torch.tensor([3.0, 4.0], requires_grad=True)
    print(temp.requires_grad)
    print((temp ** 2).requires_grad)

True
True
True
False
